/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Demon.glb 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/Demon.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="RootNode">
          <group name="CharacterArmature" rotation={[-Math.PI / 2, 0, 0]} scale={47.527}>
            <group name="Root" position={[-0.025, -0.023, -0.001]}>
              <group name="FootL" position={[0.004, 0, 0]} rotation={[-1.567, 0, Math.PI]}>
                <group name="FootL_end" position={[0, -0.006, 0]} />
              </group>
              <group name="Body" position={[0, 0.01, 0.002]}>
                <group name="Hips" position={[0, -0.002, -0.002]} rotation={[-0.102, 0, 0]}>
                  <group name="Abdomen" position={[0, 0.003, 0]} rotation={[0.182, 0, 0]}>
                    <group name="Torso" position={[0, 0.003, 0]} rotation={[0.193, 0, 0]}>
                      <group name="Neck" position={[0, 0.006, 0]} rotation={[0.719, 0, 0]}>
                        <group name="Head" position={[0, 0.002, 0]} rotation={[-0.633, -0.001, 0]}>
                          <group name="Head_end" />
                        </group>
                      </group>
                      <group name="ShoulderL" position={[0.002, 0.003, 0]} rotation={[-0.273, 0, -0.845]}>
                        <group name="UpperArmL" position={[0, 0.003, 0]} rotation={[-1.664, -0.839, -1.69]}>
                          <group name="LowerArmL" position={[0, 0.008, 0]} rotation={[0.062, 0.065, 0.021]}>
                            <group name="Pinky1L" position={[0, 0.005, 0]} rotation={[-0.015, 0.031, 0.602]}>
                              <group name="Pinky2L" position={[0, 0.002, 0]} rotation={[-0.058, 0, -0.337]}>
                                <group name="Pinky3L" position={[0, 0.001, 0]} rotation={[-0.214, -0.004, 0.017]}>
                                  <group name="Pinky3L_end" position={[0, -0.004, 0]} />
                                </group>
                              </group>
                            </group>
                            <group name="Middle1L" position={[0, 0.005, 0]} rotation={[0.049, -0.003, -0.016]}>
                              <group name="Middle2L" position={[0, 0.003, 0]} rotation={[-0.226, -0.002, 0.029]}>
                                <group name="Middle3L" position={[0, 0.001, 0]} rotation={[0.041, -0.002, -0.002]}>
                                  <group name="Middle3L_end" position={[0, -0.003, 0]} />
                                </group>
                              </group>
                            </group>
                            <group name="Index1L" position={[0, 0.005, 0]} rotation={[-0.009, -0.041, -0.63]}>
                              <group name="Index2L" position={[0, 0.003, 0]} rotation={[0.07, 0.07, 0.467]}>
                                <group name="Index3L" position={[0, 0.001, 0]} rotation={[-0.153, 0, -0.04]}>
                                  <group name="Index3L_end" position={[0, -0.004, 0]} />
                                </group>
                              </group>
                            </group>
                            <group name="Thumb1L" position={[0, 0.005, 0]} rotation={[-0.06, -0.025, -1.49]}>
                              <group name="Thumb2L" position={[0, 0.003, 0]} rotation={[-0.024, 0, 0.428]}>
                                <group name="Thumb2L_end" position={[0, -0.003, 0]} />
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                      <group name="ShoulderR" position={[-0.002, 0.003, 0]} rotation={[-0.273, 0, 0.845]}>
                        <group name="UpperArmR" position={[0, 0.003, 0]} rotation={[-1.664, 0.839, 1.69]}>
                          <group name="LowerArmR" position={[0, 0.008, 0]} rotation={[0.062, -0.065, -0.021]}>
                            <group name="Pinky1R" position={[0, 0.005, 0]} rotation={[-0.015, -0.031, -0.603]}>
                              <group name="Pinky2R" position={[0, 0.002, 0]} rotation={[-0.058, 0, 0.337]}>
                                <group name="Pinky3R" position={[0, 0.001, 0]} rotation={[-0.214, 0.004, -0.017]}>
                                  <group name="Pinky3R_end" position={[0, -0.004, 0]} />
                                </group>
                              </group>
                            </group>
                            <group name="Middle1R" position={[0, 0.005, 0]} rotation={[0.049, 0.003, 0.016]}>
                              <group name="Middle2R" position={[0, 0.003, 0]} rotation={[-0.226, 0.002, -0.029]}>
                                <group name="Middle3R" position={[0, 0.001, 0]} rotation={[0.041, 0.002, 0.002]}>
                                  <group name="Middle3R_end" position={[0, -0.003, 0]} />
                                </group>
                              </group>
                            </group>
                            <group name="Index1R" position={[0, 0.005, 0]} rotation={[-0.009, 0.041, 0.63]}>
                              <group name="Index2R" position={[0, 0.003, 0]} rotation={[0.07, -0.07, -0.467]}>
                                <group name="Index3R" position={[0, 0.001, 0]} rotation={[-0.153, 0, 0.04]}>
                                  <group name="Index3R_end" position={[0, -0.004, 0]} />
                                </group>
                              </group>
                            </group>
                            <group name="Thumb1R" position={[0, 0.005, 0]} rotation={[-0.06, 0.025, 1.49]}>
                              <group name="Thumb2R" position={[0, 0.003, 0]} rotation={[-0.024, 0, -0.428]}>
                                <group name="Thumb2R_end" position={[0, -0.003, 0]} />
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group name="UpperLegL" position={[0.003, 0, -0.002]} rotation={[3.102, -0.002, -0.021]}>
                  <group name="LowerLegL" position={[0, 0.004, 0]} rotation={[0.192, 0.006, 0.02]}>
                    <group name="LowerLegL_end" position={[0, 0.001, 0]} />
                  </group>
                </group>
                <group name="UpperLegR" position={[-0.003, 0, -0.002]} rotation={[3.102, 0.002, 0.021]}>
                  <group name="LowerLegR" position={[0, 0.004, 0]} rotation={[0.192, -0.006, -0.02]}>
                    <group name="LowerLegR_end" position={[0, 0.001, 0]} />
                  </group>
                </group>
              </group>
              <group name="PoleTargetL" position={[0.003, 0.006, 0.019]}>
                <group name="PoleTargetL_end" position={[0, -0.007, 0]} />
              </group>
              <group name="FootR" position={[-0.003, 0, 0]} rotation={[-1.567, 0, -Math.PI]}>
                <group name="FootR_end" position={[0, -0.006, 0]} />
              </group>
              <group name="PoleTargetR" position={[-0.003, 0.006, 0.019]}>
                <group name="PoleTargetR_end" position={[0, -0.007, 0]} />
              </group>
            </group>
            <group name="Demon">
              <mesh name="Demon_1" geometry={nodes.Demon_1.geometry} material={materials.Demon_Main} />
              <mesh name="Demon_2" geometry={nodes.Demon_2.geometry} material={materials.Black} />
              <mesh name="Demon_3" geometry={nodes.Demon_3.geometry} material={materials.Eye_White} />
              <mesh name="Demon_4" geometry={nodes.Demon_4.geometry} material={materials.Eye_Black} />
            </group>
            <mesh name="Trident" geometry={nodes.Trident.geometry} material={materials.Black} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Demon.glb')
