/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/sky.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/sky.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Bench_A_0036__M_Cnsw_11_F_Obj_01_Bench_A_0036__M_Cnsw_11_F_.geometry} material={materials.M_Cnsw_11_F_Obj_01_1} position={[2.114, 8.333, 35.059]} />
      <mesh geometry={nodes.Bench_A_0036__M_Cnsw_11_F_Obj_01_Bench_A_0036__M_Cnsw_11_F_001.geometry} material={materials.M_Cnsw_11_F_Obj_01_1} position={[21.348, -1.276, 30.799]} />
      <mesh geometry={nodes.Bench_A_0036__M_Cnsw_11_F_Obj_01_Bench_A_0036__M_Cnsw_11_F_002.geometry} material={materials.M_Cnsw_11_F_Obj_01_1} position={[-5.004, -6.64, 39.165]} />
      <mesh geometry={nodes.Bench_A_0036__M_Cnsw_11_F_Obj_01_Bench_A_0036__M_Cnsw_11_F_003.geometry} material={materials.M_Cnsw_11_F_Obj_01_1} position={[9.691, 1.045, 29.013]} />
      <mesh geometry={nodes.Bench_A_0036__M_Cnsw_11_F_Obj_01_Bench_A_0036__M_Cnsw_11_F_004.geometry} material={materials.M_Cnsw_11_F_Obj_01_1} position={[20.165, 1.419, 23.359]} />
      <mesh geometry={nodes.Bench_A_0036__M_Cnsw_11_F_Obj_01_Bench_A_0036__M_Cnsw_11_F_005.geometry} material={materials.M_Cnsw_11_F_Obj_01_1} position={[14.398, 4.124, 36.027]} />
    </group>
  )
}

useGLTF.preload('/sky.glb')
