/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/sky.glb 
*/

import { Cloud, Clouds, Float, useGLTF } from '@react-three/drei'
import { useControls } from 'leva'
import * as THREE from 'three'

export function Sky() {
    const { nodes, materials } = useGLTF('models/sky.glb')
    const { x, y, z, ...config } = useControls({
        seed: { value: 1, min: 1, max: 100, step: 1 },
        segments: { value: 20, min: 1, max: 80, step: 1 },
        volume: { value: 6, min: 0, max: 100, step: 0.1 },
        opacity: { value: 0.8, min: 0, max: 1, step: 0.01 },
        fade: { value: 77, min: 0, max: 400, step: 1 },
        growth: { value: 4, min: 0, max: 20, step: 1 },
        speed: { value: 0.1, min: 0, max: 1, step: 0.01 },
        x: { value: 43, min: 0, max: 100, step: 1 },
        y: { value: 1, min: 0, max: 100, step: 1 },
        z: { value: 1, min: 0, max: 100, step: 1 },
    })
    return (
        <group dispose={null}>
            <Clouds material={THREE.MeshLambertMaterial} limit={400} >
                <Cloud {...config} bounds={[x, y, z]} color="white" seed={2} position={[2.114, 8.333, 35.059]} />
                <Cloud {...config} bounds={[x, y, z]} color="white" seed={3} position={[21.348, -1.276, 30.799]} />
                <Cloud {...config} bounds={[x, y, z]} color="white" seed={4} position={[-5.004, -6.64, 39.165]} />
                {/* <Cloud {...config} bounds={[x, y, z]} color="white" seed={5} position={[20.165, 1.419, 23.359]} /> */}
            </Clouds>
            <Float
                speed={.5} // Animation speed, defaults to 1
                rotationIntensity={0.5} // Rotation intensity, defaults to 1
                floatIntensity={0.5} // Float intensity, defaults to 1
            >
                <mesh geometry={(nodes.Bench_A_0036__M_Cnsw_11_F_Obj_01_Bench_A_0036__M_Cnsw_11_F_ as THREE.Mesh).geometry} material={materials.M_Cnsw_11_F_Obj_01_1} position={[2.114, 8.333, 35.059]} >

                </mesh>

            </Float>
            <Float
                speed={.5} // Animation speed, defaults to 1
                rotationIntensity={0.5} // Rotation intensity, defaults to 1
                floatIntensity={0.5} // Float intensity, defaults to 1
            >
                <mesh geometry={(nodes.Bench_A_0036__M_Cnsw_11_F_Obj_01_Bench_A_0036__M_Cnsw_11_F_001 as THREE.Mesh).geometry} material={materials.M_Cnsw_11_F_Obj_01_1} position={[21.348, -1.276, 30.799]} />

            </Float>
            <Float
                speed={.5} // Animation speed, defaults to 1
                rotationIntensity={0.5} // Rotation intensity, defaults to 1
                floatIntensity={0.5} // Float intensity, defaults to 1
            >
                <mesh geometry={(nodes.Bench_A_0036__M_Cnsw_11_F_Obj_01_Bench_A_0036__M_Cnsw_11_F_002 as THREE.Mesh).geometry} material={materials.M_Cnsw_11_F_Obj_01_1} position={[-5.004, -6.64, 39.165]} />

            </Float>
            <Float
                speed={.5} // Animation speed, defaults to 1
                rotationIntensity={0.5} // Rotation intensity, defaults to 1
                floatIntensity={0.5} // Float intensity, defaults to 1
            >
                <mesh geometry={(nodes.Bench_A_0036__M_Cnsw_11_F_Obj_01_Bench_A_0036__M_Cnsw_11_F_003 as THREE.Mesh).geometry} material={materials.M_Cnsw_11_F_Obj_01_1} position={[9.691, 1.045, 29.013]} />

            </Float>
            <Float
                speed={.5} // Animation speed, defaults to 1
                rotationIntensity={0.5} // Rotation intensity, defaults to 1
                floatIntensity={0.5} // Float intensity, defaults to 1
            >
                <mesh geometry={(nodes.Bench_A_0036__M_Cnsw_11_F_Obj_01_Bench_A_0036__M_Cnsw_11_F_004 as THREE.Mesh).geometry} material={materials.M_Cnsw_11_F_Obj_01_1} position={[20.165, 1.419, 23.359]} />

            </Float>
            <Float
                speed={.5} // Animation speed, defaults to 1
                rotationIntensity={0.5} // Rotation intensity, defaults to 1
                floatIntensity={0.5} // Float intensity, defaults to 1
            >
                <mesh geometry={(nodes.Bench_A_0036__M_Cnsw_11_F_Obj_01_Bench_A_0036__M_Cnsw_11_F_005 as THREE.Mesh).geometry} material={materials.M_Cnsw_11_F_Obj_01_1} position={[14.398, 4.124, 36.027]} />

            </Float>

        </group>
    )
}

useGLTF.preload('/sky.glb')
